#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash.d/display
# author:   Mike Redd
# version:  1.0
# desc:     Display/WM auto-start configuration
#--------------------------------------------

if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR:-0}" -eq 1 ]; then
    startx
fi
