#--------------------------------------------
# file:     ThemeEngine.ps1
# author:   Mike Redd
# version:  0.1-dev
# desc:     Typezero ThemeEngine — Netzach PowerShell renderer
#--------------------------------------------

param(
    [Parameter(Position = 0)]
    [ValidateSet("bootstrap","list","current","preview","apply","reload","rollback","doctor","help")]
    [string]$Command = "help",

    [Parameter(Position = 1)]
    [string]$Theme,

    [string]$RepoRoot
)

$ErrorActionPreference = "Stop"

$EngineRoot   = Join-Path $env:LOCALAPPDATA "Typezero\ThemeEngine"
$ThemesRoot   = Join-Path $EngineRoot "themes"
$TemplatesRoot = Join-Path $EngineRoot "templates"
$CurrentFile  = Join-Path $EngineRoot "current-theme"
$PreviousFile = Join-Path $EngineRoot "previous-theme"
$CurrentPs1   = Join-Path $EngineRoot "current.ps1"

New-Item -ItemType Directory -Force -Path $EngineRoot | Out-Null

function Read-ThemeFile {
    param([Parameter(Mandatory)][string]$Id)

    $path = Join-Path (Join-Path $ThemesRoot $Id) "theme.conf"
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Theme not found: $Id"
    }

    $result = [ordered]@{}
    foreach ($raw in Get-Content -LiteralPath $path) {
        $line = $raw.Trim()
        if (-not $line -or $line.StartsWith("#") -or -not $line.Contains("=")) { continue }

        $idx = $line.IndexOf("=")
        $key = $line.Substring(0, $idx).Trim()
        $val = $line.Substring($idx + 1).Trim()

        if (($val.StartsWith('"') -and $val.EndsWith('"')) -or
            ($val.StartsWith("'") -and $val.EndsWith("'"))) {
            $val = $val.Substring(1, $val.Length - 2)
        }

        $result[$key] = $val
    }

    # Interaction-state roles extend the semantic palette without breaking
    # existing themes. Missing values inherit the exact roles ThemeEngine
    # historically used for these surfaces.
    if (-not $result.Contains("SELECTION") -or -not $result["SELECTION"]) {
        $result["SELECTION"] = $result["BORDER"]
    }
    if (-not $result.Contains("CURSOR") -or -not $result["CURSOR"]) {
        $result["CURSOR"] = $result["ACCENT_BRIGHT"]
    }
    if (-not $result.Contains("FOCUS") -or -not $result["FOCUS"]) {
        $result["FOCUS"] = $result["ACCENT"]
    }

    return $result
}

function Write-ThemeTemplate {
    param(
        [Parameter(Mandatory)][string]$Source,
        [Parameter(Mandatory)][string]$Destination,
        [Parameter(Mandatory)][System.Collections.IDictionary]$Theme
    )

    # Shared templates use {{ROLE}} tokens matching theme.conf keys. Rendering
    # from the parsed theme dictionary keeps consumer files palette-agnostic
    # and gives Windows the same template contract used by Arakiel.
    if (-not (Test-Path -LiteralPath $Source)) {
        throw "Theme template not found: $Source"
    }

    $content = Get-Content -LiteralPath $Source -Raw
          # Vim runtime files must use deterministic LF endings on every platform.
    # Normalizing template input here prevents carriage returns from surviving
    # rendering as literal ^M characters that Vim interprets as command text.
    $content = $content -replace "`r`n", "`n"
    $content = $content -replace "`r", "`n"

    foreach ($key in $Theme.Keys) {
        $content = $content.Replace("{{$key}}", [string]$Theme[$key])
    }

    $parent = Split-Path -Parent $Destination
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
    Set-Content -LiteralPath $Destination -Value $content -NoNewline -Encoding utf8
}
function Convert-HexToAnsi {
    param([Parameter(Mandatory)][string]$Hex)

    $h = $Hex.TrimStart("#")
    if ($h.Length -ne 6) { throw "Invalid RGB color: $Hex" }

    $r = [Convert]::ToInt32($h.Substring(0, 2), 16)
    $g = [Convert]::ToInt32($h.Substring(2, 2), 16)
    $b = [Convert]::ToInt32($h.Substring(4, 2), 16)

    return "$([char]27)[38;2;$r;$g;$($b)m"
}

function Write-CurrentTheme {
    param([Parameter(Mandatory)][System.Collections.IDictionary]$T)

    $name      = $T["THEME_NAME"].Replace("'", "''")
    $id        = $T["THEME_ID"].Replace("'", "''")

    $accent    = Convert-HexToAnsi $T["ACCENT"]
    $accentHi  = Convert-HexToAnsi $T["ACCENT_BRIGHT"]
    $success   = Convert-HexToAnsi $T["SUCCESS"]
    $warning   = Convert-HexToAnsi $T["WARNING"]
    $error     = Convert-HexToAnsi $T["ERROR"]
    $muted     = Convert-HexToAnsi $T["MUTED"]
    $text      = Convert-HexToAnsi $T["TEXT"]
    $bright    = Convert-HexToAnsi $T["BRIGHT"]
    $secondary = Convert-HexToAnsi $T["SECONDARY"]
    $info      = Convert-HexToAnsi $T["INFO"]

    $content = @"
# Generated by Typezero ThemeEngine — $name
`$esc = [char]27
`$global:TE_Theme = [ordered]@{
    Id           = '$id'
    Name         = '$name'
    Accent       = '$accent'
    AccentBright = '$accentHi'
    Success      = '$success'
    Warning      = '$warning'
    Error        = '$error'
    Muted        = '$muted'
    Text         = '$text'
    Bright       = '$bright'
    Secondary    = '$secondary'
    Info         = '$info'
    Reset        = "`$esc[0m"
    Bold         = "`$esc[1m"
    Dim          = "`$esc[2m"
}
"@

    Set-Content -LiteralPath $CurrentPs1 -Value $content -Encoding utf8
}

function Get-WindowsTerminalSettingsPath {
    # Windows Terminal's packaged settings location. ThemeEngine deliberately
    # manages only the named Typezero scheme and the PowerShell profile's
    # colorScheme property; unrelated Terminal settings remain untouched.
    $packagePath = Join-Path $env:LOCALAPPDATA `
        "Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"

    if (Test-Path -LiteralPath $packagePath) {
        return $packagePath
    }

    return $null
}

function Set-WindowsTerminalTheme {
    param([Parameter(Mandatory)][System.Collections.IDictionary]$T)

    $settingsPath = Get-WindowsTerminalSettingsPath
    if (-not $settingsPath) {
        return
    }

    # A complete ANSI palette is required before ThemeEngine touches Terminal.
    # Themes without one remain valid for other renderers and are simply
    # skipped here rather than receiving guessed or partially mapped colors.
    $ansiKeys = @(
        "ANSI_BLACK",
        "ANSI_RED",
        "ANSI_GREEN",
        "ANSI_YELLOW",
        "ANSI_BLUE",
        "ANSI_PURPLE",
        "ANSI_CYAN",
        "ANSI_WHITE",
        "ANSI_BRIGHT_BLACK",
        "ANSI_BRIGHT_RED",
        "ANSI_BRIGHT_GREEN",
        "ANSI_BRIGHT_YELLOW",
        "ANSI_BRIGHT_BLUE",
        "ANSI_BRIGHT_PURPLE",
        "ANSI_BRIGHT_CYAN",
        "ANSI_BRIGHT_WHITE"
    )

    foreach ($key in $ansiKeys) {
        if (-not $T.Contains($key) -or -not $T[$key]) {
            Write-Host "Windows Terminal: skipped (theme has no complete ANSI palette)"
            return
        }
    }

    $settings = Get-Content -LiteralPath $settingsPath -Raw |
        ConvertFrom-Json

    # Preserve the user's original file before ThemeEngine's first write.
    # This is intentionally a stable backup rather than a rotating snapshot:
    # it represents the pre-ThemeEngine Windows Terminal configuration.
    $backupPath = "$settingsPath.typezero-backup"
    if (-not (Test-Path -LiteralPath $backupPath)) {
        Copy-Item -LiteralPath $settingsPath -Destination $backupPath
    }

    $schemeName = "Typezero $($T['THEME_NAME'])"

    $scheme = [ordered]@{
        name                = $schemeName
        background          = $T["BG"]
        foreground          = $T["TEXT"]
        cursorColor         = $T["CURSOR"]
        selectionBackground = $T["SELECTION"]
        black               = $T["ANSI_BLACK"]
        red                 = $T["ANSI_RED"]
        green               = $T["ANSI_GREEN"]
        yellow              = $T["ANSI_YELLOW"]
        blue                = $T["ANSI_BLUE"]
        purple              = $T["ANSI_PURPLE"]
        cyan                = $T["ANSI_CYAN"]
        white               = $T["ANSI_WHITE"]
        brightBlack         = $T["ANSI_BRIGHT_BLACK"]
        brightRed           = $T["ANSI_BRIGHT_RED"]
        brightGreen         = $T["ANSI_BRIGHT_GREEN"]
        brightYellow        = $T["ANSI_BRIGHT_YELLOW"]
        brightBlue          = $T["ANSI_BRIGHT_BLUE"]
        brightPurple        = $T["ANSI_BRIGHT_PURPLE"]
        brightCyan          = $T["ANSI_BRIGHT_CYAN"]
        brightWhite         = $T["ANSI_BRIGHT_WHITE"]
    }

    # Replace only ThemeEngine's scheme for this theme. Other custom schemes
    # remain untouched.
    $otherSchemes = @(
        $settings.schemes |
            Where-Object { $_.name -ne $schemeName }
    )

    $settings.schemes = @($otherSchemes) + @([pscustomobject]$scheme)

    # Keep Windows Terminal's application chrome visually aligned with the
    # active Typezero palette. The active tab follows the terminal pane while
    # the surrounding tab row uses the theme background. This deliberately
    # leaves profile-specific wallpaper, opacity, typography, and other user
    # preferences untouched.
    $terminalThemeName = "Typezero ThemeEngine"

    $terminalTheme = [ordered]@{
        name = $terminalThemeName
        window = [ordered]@{
            applicationTheme = "dark"
        }
        tab = [ordered]@{
            background          = "terminalBackground"
            unfocusedBackground = $T["BG"]
            showCloseButton      = "hover"
        }
        tabRow = [ordered]@{
            background          = $T["BG"]
            unfocusedBackground = $T["BG"]
        }
    }

    $existingThemes = @(
        $settings.themes |
            Where-Object { $_.name -ne $terminalThemeName }
    )

    $settings.themes = @($existingThemes) + @([pscustomobject]$terminalTheme)
    if ($settings.PSObject.Properties["theme"]) {
        $settings.theme = $terminalThemeName
    } else {
        $settings | Add-Member -NotePropertyName theme -NotePropertyValue $terminalThemeName
    }

    # Target PowerShell 7 by its stable Windows Terminal profile GUID rather
    # than relying solely on a display name that the user may rename.
    $powerShellGuid = "{574e775e-4f2a-5b96-ac1e-a2962a402336}"
    $profile = $settings.profiles.list |
        Where-Object { $_.guid -eq $powerShellGuid } |
        Select-Object -First 1

    if (-not $profile) {
        throw "Windows Terminal PowerShell profile not found: $powerShellGuid"
    }

    if ($profile.PSObject.Properties["colorScheme"]) {
        $profile.colorScheme = $schemeName
    } else {
        $profile | Add-Member -NotePropertyName colorScheme -NotePropertyValue $schemeName
    }

    # ConvertFrom/To-Json necessarily reformats settings.json, but preserves
    # its data. ThemeEngine changes only the scheme collection described above
    # and the PowerShell profile's colorScheme association.
    $json = $settings | ConvertTo-Json -Depth 100
    Set-Content -LiteralPath $settingsPath -Value $json -Encoding utf8

    Write-Host "Windows Terminal: $schemeName"
}
function Set-Theme {
    param(
        [Parameter(Mandatory)][string]$Id,
        [switch]$NoHistory
    )

    $t = Read-ThemeFile $Id

    if (-not $NoHistory -and (Test-Path -LiteralPath $CurrentFile)) {
        $old = (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        if ($old -and $old -ne $Id) {
            Set-Content -LiteralPath $PreviousFile -Value $old -Encoding ascii
        }
    }

    Write-CurrentTheme $t

    # Vim receives a generated native colorscheme from the same semantic
    # palette used by the shell and Windows Terminal. Keep the output inside
    # Netzach's established Vim config tree rather than a second runtime.
    $vimTemplate = Join-Path $TemplatesRoot 'shared\vim-colors.vim.tpl'
    $vimColors = Join-Path $HOME 'config\vim\colors\typezero.vim'
    Write-ThemeTemplate -Source $vimTemplate -Destination $vimColors -Theme $t

    # Lightline uses its own colorscheme API rather than Vim highlight groups.
    # Generate its palette beside the native Vim theme so both surfaces follow
    # the same ThemeEngine semantic roles and switch together.
    $lightlineTemplate = Join-Path $TemplatesRoot 'shared\vim-lightline.vim.tpl'
    $lightlineColors = Join-Path $HOME 'config\vim\autoload\lightline\colorscheme\typezero.vim'
    Write-ThemeTemplate -Source $lightlineTemplate -Destination $lightlineColors -Theme $t

    Set-WindowsTerminalTheme $t
    Set-Content -LiteralPath $CurrentFile -Value $Id -Encoding ascii
    Write-Host "Applied theme: $($t['THEME_NAME'])"
}

switch ($Command) {
    "bootstrap" {
        if (-not $RepoRoot) { $RepoRoot = (Get-Location).Path }
        $themeSource = Join-Path $RepoRoot "ThemeEngine\themes"
        $templateSource = Join-Path $RepoRoot "ThemeEngine\templates"

        if (-not (Test-Path -LiteralPath $themeSource)) {
            throw "ThemeEngine\themes not found under: $RepoRoot"
        }
        if (-not (Test-Path -LiteralPath $templateSource)) {
            throw "ThemeEngine\templates not found under: $RepoRoot"
        }

        # Bootstrap themes and templates together so normal operation uses
        # installed ThemeEngine data rather than the development repository.
        foreach ($installRoot in @($ThemesRoot, $TemplatesRoot)) {
            if (Test-Path -LiteralPath $installRoot) {
                Remove-Item -LiteralPath $installRoot -Recurse -Force
            }
            New-Item -ItemType Directory -Force -Path $installRoot | Out-Null
        }

        Copy-Item -Path (Join-Path $themeSource "*") -Destination $ThemesRoot -Recurse -Force
        Copy-Item -Path (Join-Path $templateSource "*") -Destination $TemplatesRoot -Recurse -Force

        Write-Host "ThemeEngine themes installed under $ThemesRoot"
        Write-Host "ThemeEngine templates installed under $TemplatesRoot"
    }

    "list" {
        if (-not (Test-Path -LiteralPath $ThemesRoot)) {
            throw "No themes installed. Run ThemeEngine.ps1 bootstrap -RepoRoot <repo-root>"
        }

        $current = if (Test-Path -LiteralPath $CurrentFile) {
            (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        } else { "" }

        Get-ChildItem -LiteralPath $ThemesRoot -Directory | ForEach-Object {
            $prefix = if ($_.Name -eq $current) { "*" } else { " " }
            Write-Host "$prefix $($_.Name)"
        }
    }

    "current" {
        if (Test-Path -LiteralPath $CurrentFile) {
            (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        } else {
            "none"
        }
    }

    "preview" {
        if (-not $Theme) {
            if (-not (Test-Path -LiteralPath $CurrentFile)) { throw "No theme selected." }
            $Theme = (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        }

        $t = Read-ThemeFile $Theme
        Write-Host ""
        Write-Host "  $($t['THEME_NAME'])"
        Write-Host ""

        foreach ($role in @("ACCENT","ACCENT_BRIGHT","SELECTION","CURSOR","FOCUS","TEXT","MUTED","SUCCESS","WARNING","ERROR","SECONDARY","INFO")) {
            $c = Convert-HexToAnsi $t[$role]
            Write-Host "$c  $($role.PadRight(14)) $($t[$role])$([char]27)[0m"
        }

        Write-Host ""
    }

    "apply" {
        if (-not $Theme) { throw "Usage: ThemeEngine.ps1 apply <theme>" }
        Set-Theme $Theme
    }

    "reload" {
        if (-not (Test-Path -LiteralPath $CurrentFile)) { throw "No current theme." }
        $id = (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        Set-Theme $id -NoHistory
    }

    "rollback" {
        if (-not (Test-Path -LiteralPath $PreviousFile)) { throw "No previous theme." }
        $id = (Get-Content -LiteralPath $PreviousFile -Raw).Trim()
        Set-Theme $id
    }

    "doctor" {
        Write-Host "ThemeEngine doctor"
        Write-Host ""
        Write-Host ("  themes        " + $(if (Test-Path $ThemesRoot) { "PASS" } else { "MISSING" }))
        Write-Host ("  current       " + $(if (Test-Path $CurrentFile) { (Get-Content $CurrentFile -Raw).Trim() } else { "none" }))
        Write-Host ("  renderer      PowerShell $($PSVersionTable.PSVersion)")
        Write-Host ("  current.ps1   " + $(if (Test-Path $CurrentPs1) { "PASS" } else { "MISSING" }))
        $terminalSettings = Get-WindowsTerminalSettingsPath
        Write-Host ("  terminal      " + $(if ($terminalSettings) { "PASS" } else { "NOT FOUND" }))
    }

    default {
        @"
Typezero ThemeEngine

usage:
  ThemeEngine.ps1 bootstrap -RepoRoot <repo-root>
  ThemeEngine.ps1 list
  ThemeEngine.ps1 current
  ThemeEngine.ps1 preview [theme]
  ThemeEngine.ps1 apply <theme>
  ThemeEngine.ps1 reload
  ThemeEngine.ps1 rollback
  ThemeEngine.ps1 doctor
"@
    }
}
