#--------------------------------------------
# file:     ThemeEngine.ps1
# author:   Mike Redd
# version:  0.1-dev
# desc:     Typezero ThemeEngine — Netzach PowerShell renderer
#--------------------------------------------

param(
    [Parameter(Position = 0)]
    [ValidateSet("bootstrap","list","current","preview","apply","reload","rollback","doctor","help")]
    [string]$Command = "help",

    [Parameter(Position = 1)]
    [string]$Theme,

    [string]$RepoRoot
)

$ErrorActionPreference = "Stop"

$EngineRoot   = Join-Path $env:LOCALAPPDATA "Typezero\ThemeEngine"
$ThemesRoot   = Join-Path $EngineRoot "themes"
$CurrentFile  = Join-Path $EngineRoot "current-theme"
$PreviousFile = Join-Path $EngineRoot "previous-theme"
$CurrentPs1   = Join-Path $EngineRoot "current.ps1"

New-Item -ItemType Directory -Force -Path $EngineRoot | Out-Null

function Read-ThemeFile {
    param([Parameter(Mandatory)][string]$Id)

    $path = Join-Path (Join-Path $ThemesRoot $Id) "theme.conf"
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Theme not found: $Id"
    }

    $result = [ordered]@{}
    foreach ($raw in Get-Content -LiteralPath $path) {
        $line = $raw.Trim()
        if (-not $line -or $line.StartsWith("#") -or -not $line.Contains("=")) { continue }

        $idx = $line.IndexOf("=")
        $key = $line.Substring(0, $idx).Trim()
        $val = $line.Substring($idx + 1).Trim()

        if (($val.StartsWith('"') -and $val.EndsWith('"')) -or
            ($val.StartsWith("'") -and $val.EndsWith("'"))) {
            $val = $val.Substring(1, $val.Length - 2)
        }

        $result[$key] = $val
    }

    return $result
}

function Convert-HexToAnsi {
    param([Parameter(Mandatory)][string]$Hex)

    $h = $Hex.TrimStart("#")
    if ($h.Length -ne 6) { throw "Invalid RGB color: $Hex" }

    $r = [Convert]::ToInt32($h.Substring(0, 2), 16)
    $g = [Convert]::ToInt32($h.Substring(2, 2), 16)
    $b = [Convert]::ToInt32($h.Substring(4, 2), 16)

    return "$([char]27)[38;2;$r;$g;${b}m"
}

function Write-CurrentTheme {
    param([Parameter(Mandatory)][System.Collections.IDictionary]$T)

    $name      = $T["THEME_NAME"].Replace("'", "''")
    $id        = $T["THEME_ID"].Replace("'", "''")

    $accent    = Convert-HexToAnsi $T["ACCENT"]
    $accentHi  = Convert-HexToAnsi $T["ACCENT_BRIGHT"]
    $success   = Convert-HexToAnsi $T["SUCCESS"]
    $warning   = Convert-HexToAnsi $T["WARNING"]
    $error     = Convert-HexToAnsi $T["ERROR"]
    $muted     = Convert-HexToAnsi $T["MUTED"]
    $text      = Convert-HexToAnsi $T["TEXT"]
    $bright    = Convert-HexToAnsi $T["BRIGHT"]
    $secondary = Convert-HexToAnsi $T["SECONDARY"]
    $info      = Convert-HexToAnsi $T["INFO"]

    $content = @"
# Generated by Typezero ThemeEngine — $name
`$esc = [char]27
`$global:TE_Theme = [ordered]@{
    Id           = '$id'
    Name         = '$name'
    Accent       = '$accent'
    AccentBright = '$accentHi'
    Success      = '$success'
    Warning      = '$warning'
    Error        = '$error'
    Muted        = '$muted'
    Text         = '$text'
    Bright       = '$bright'
    Secondary    = '$secondary'
    Info         = '$info'
    Reset        = "`$esc[0m"
    Bold         = "`$esc[1m"
    Dim          = "`$esc[2m"
}
"@

    Set-Content -LiteralPath $CurrentPs1 -Value $content -Encoding utf8
}

function Set-Theme {
    param(
        [Parameter(Mandatory)][string]$Id,
        [switch]$NoHistory
    )

    $t = Read-ThemeFile $Id

    if (-not $NoHistory -and (Test-Path -LiteralPath $CurrentFile)) {
        $old = (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        if ($old -and $old -ne $Id) {
            Set-Content -LiteralPath $PreviousFile -Value $old -Encoding ascii
        }
    }

    Write-CurrentTheme $t
    Set-Content -LiteralPath $CurrentFile -Value $Id -Encoding ascii
    Write-Host "Applied theme: $($t['THEME_NAME'])"
}

switch ($Command) {
    "bootstrap" {
        if (-not $RepoRoot) { $RepoRoot = (Get-Location).Path }
        $source = Join-Path $RepoRoot "ThemeEngine\themes"
        if (-not (Test-Path -LiteralPath $source)) {
            throw "ThemeEngine\themes not found under: $RepoRoot"
        }

        if (Test-Path -LiteralPath $ThemesRoot) {
            Remove-Item -LiteralPath $ThemesRoot -Recurse -Force
        }

        New-Item -ItemType Directory -Force -Path $ThemesRoot | Out-Null
        Copy-Item -Path (Join-Path $source "*") -Destination $ThemesRoot -Recurse -Force
        Write-Host "ThemeEngine themes installed under $ThemesRoot"
    }

    "list" {
        if (-not (Test-Path -LiteralPath $ThemesRoot)) {
            throw "No themes installed. Run ThemeEngine.ps1 bootstrap -RepoRoot <repo-root>"
        }

        $current = if (Test-Path -LiteralPath $CurrentFile) {
            (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        } else { "" }

        Get-ChildItem -LiteralPath $ThemesRoot -Directory | ForEach-Object {
            $prefix = if ($_.Name -eq $current) { "*" } else { " " }
            Write-Host "$prefix $($_.Name)"
        }
    }

    "current" {
        if (Test-Path -LiteralPath $CurrentFile) {
            (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        } else {
            "none"
        }
    }

    "preview" {
        if (-not $Theme) {
            if (-not (Test-Path -LiteralPath $CurrentFile)) { throw "No theme selected." }
            $Theme = (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        }

        $t = Read-ThemeFile $Theme
        Write-Host ""
        Write-Host "  $($t['THEME_NAME'])"
        Write-Host ""

        foreach ($role in @("ACCENT","ACCENT_BRIGHT","TEXT","MUTED","SUCCESS","WARNING","ERROR","SECONDARY","INFO")) {
            $c = Convert-HexToAnsi $t[$role]
            Write-Host "$c  $($role.PadRight(14)) $($t[$role])$([char]27)[0m"
        }

        Write-Host ""
    }

    "apply" {
        if (-not $Theme) { throw "Usage: ThemeEngine.ps1 apply <theme>" }
        Set-Theme $Theme
    }

    "reload" {
        if (-not (Test-Path -LiteralPath $CurrentFile)) { throw "No current theme." }
        $id = (Get-Content -LiteralPath $CurrentFile -Raw).Trim()
        Set-Theme $id -NoHistory
    }

    "rollback" {
        if (-not (Test-Path -LiteralPath $PreviousFile)) { throw "No previous theme." }
        $id = (Get-Content -LiteralPath $PreviousFile -Raw).Trim()
        Set-Theme $id
    }

    "doctor" {
        Write-Host "ThemeEngine doctor"
        Write-Host ""
        Write-Host ("  themes        " + $(if (Test-Path $ThemesRoot) { "PASS" } else { "MISSING" }))
        Write-Host ("  current       " + $(if (Test-Path $CurrentFile) { (Get-Content $CurrentFile -Raw).Trim() } else { "none" }))
        Write-Host ("  renderer      PowerShell $($PSVersionTable.PSVersion)")
        Write-Host ("  current.ps1   " + $(if (Test-Path $CurrentPs1) { "PASS" } else { "MISSING" }))
    }

    default {
        @"
Typezero ThemeEngine

usage:
  ThemeEngine.ps1 bootstrap -RepoRoot <repo-root>
  ThemeEngine.ps1 list
  ThemeEngine.ps1 current
  ThemeEngine.ps1 preview [theme]
  ThemeEngine.ps1 apply <theme>
  ThemeEngine.ps1 reload
  ThemeEngine.ps1 rollback
  ThemeEngine.ps1 doctor
"@
    }
}
