# Generated by Typezero ThemeEngine.
# theme: {{THEME_NAME}}
# Do not edit the live copy by hand.

# ── Status Bar ─────────────────────────────

bar {
    position top
    height {{BAR_HEIGHT}}

    status_command i3blocks -c ~/.config/i3/i3blocks.conf

    font pango:{{BAR_FONT}}

    tray_output none
    strip_workspace_numbers no

    colors {
        background {{BG}}
        statusline {{TEXT}}
        separator  {{BORDER}}

        focused_workspace  {{FOCUSED_BORDER}} {{FOCUSED_BG}} {{BRIGHT}}
        active_workspace   {{ACTIVE_BORDER}} {{ACTIVE_BG}} {{TEXT}}
        inactive_workspace {{INACTIVE_BORDER}} {{INACTIVE_BG}} {{MUTED}}
        urgent_workspace   {{URGENT_BORDER}} {{URGENT_BG}} {{BRIGHT}}
    }
}

# ── Client Colors ──────────────────────────

client.focused          {{FOCUSED_BORDER}} {{FOCUSED_BG}} {{BRIGHT}} {{ACCENT}}
client.unfocused        {{INACTIVE_BORDER}} {{INACTIVE_BG}} {{MUTED}} {{BORDER_DARK}}
client.focused_inactive {{ACTIVE_BORDER}} {{ACTIVE_BG}} {{TEXT}} {{BORDER}}
client.urgent           {{URGENT_BORDER}} {{URGENT_BG}} {{BRIGHT}} {{URGENT_BORDER}}
