# Generated by Typezero ThemeEngine — {{THEME_NAME}}

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-left-length 48
set -g status-right-length 120

set -g status-style "bg={{BG}},fg={{TEXT}}"
set -g message-style "bg={{SURFACE_ALT}},fg={{BRIGHT}},bold"
set -g message-command-style "bg={{SURFACE_ALT}},fg={{BRIGHT}}"
set -g mode-style "bg={{ACCENT_BRIGHT}},fg={{BG}},bold"

set -g status-left "#[bg={{ACCENT_BRIGHT}},fg={{BG}},bold]  #S  "

setw -g window-status-separator " "
setw -g window-status-style "bg={{BG}},fg={{MUTED}}"
setw -g window-status-format " #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-current-style "bg={{FOCUS}},fg={{BG}},bold"
setw -g window-status-current-format " #I:#W#{?window_flags,#{window_flags},} "
setw -g window-status-activity-style "bg={{BG}},fg={{WARNING}},bold"
setw -g window-status-bell-style "bg={{ERROR}},fg={{BG}},bold"

set -g status-right \
"#{?pane_synchronized,#[fg={{WARNING}},bold] SYNC #[default],}\
#{?client_prefix,#[fg={{ERROR}},bold] PREFIX #[default],}\
#(~/.config/tmux/scripts/system-status.sh --status) \
#[fg={{TEXT}}]%Y-%m-%d #[bold]%H:%M:%S "

set -g pane-border-status top
set -g pane-border-style "fg={{BORDER_DARK}}"
set -g pane-active-border-style "fg={{ACCENT_BRIGHT}}"
set -g pane-border-format " #{?pane_dead,#[fg={{ERROR}},bold]DEAD ,}#{?pane_active,#[bold],}#{pane_index}: #{pane_title} #[fg={{MUTED}}]#{pane_current_command} "

set -g popup-style "bg={{SURFACE}},fg={{TEXT}}"
set -g popup-border-style "fg={{BORDER}}"
set -g menu-style "bg={{SURFACE}},fg={{TEXT}}"
set -g menu-selected-style "bg={{ACCENT}},fg={{BG}},bold"
set -g menu-border-style "fg={{BORDER}}"
