! Generated by Typezero ThemeEngine — {{THEME_NAME}}

! ThemeEngine is the authoritative owner of URxvt theme-dependent appearance.
! The active theme supplies the terminal background, foreground, cursor,
! typography, and ANSI palette through this generated resource file.
URxvt*background: {{BG}}
URxvt*foreground: {{TEXT}}
URxvt*cursorColor: {{ACCENT_BRIGHT}}

! URxvt pseudo-transparency exposes the rotating Arakiel wallpaper without a
! compositor. Tinting with the active theme background preserves each palette's
! character while shading keeps the terminal readable over detailed artwork.
URxvt*transparent: true
URxvt*tint: {{BG}}
URxvt*shading: 80

URxvt*font: xft:{{XFT_FONT}}
URxvt*letterSpace: 0
URxvt*scrollBar: false

! Theme-defined ANSI palette mapped from shared semantic roles.
URxvt*color0:  {{BG}}
URxvt*color1:  {{ERROR}}
URxvt*color2:  {{SUCCESS}}
URxvt*color3:  {{WARNING}}
URxvt*color4:  {{INFO}}
URxvt*color5:  {{SECONDARY}}
URxvt*color6:  {{ACCENT}}
URxvt*color7:  {{TEXT}}

URxvt*color8:  {{BORDER}}
URxvt*color9:  {{ERROR}}
URxvt*color10: {{SUCCESS}}
URxvt*color11: {{WARNING}}
URxvt*color12: {{ACCENT_BRIGHT}}
URxvt*color13: {{SECONDARY}}
URxvt*color14: {{INFO}}
URxvt*color15: {{BRIGHT}}
