! Generated by Typezero ThemeEngine — {{THEME_NAME}}

URxvt*background: {{BG}}
URxvt*foreground: {{TEXT}}
URxvt*cursorColor: {{ACCENT_BRIGHT}}

URxvt*font: xft:{{XFT_FONT}}
URxvt*letterSpace: 0
URxvt*scrollBar: false

! Mostly black / silver ANSI palette with restrained semantic accents.
URxvt*color0:  {{BG}}
URxvt*color1:  {{ERROR}}
URxvt*color2:  {{SUCCESS}}
URxvt*color3:  {{WARNING}}
URxvt*color4:  {{INFO}}
URxvt*color5:  {{SECONDARY}}
URxvt*color6:  {{ACCENT}}
URxvt*color7:  {{TEXT}}

URxvt*color8:  {{BORDER}}
URxvt*color9:  {{ERROR}}
URxvt*color10: {{SUCCESS}}
URxvt*color11: {{WARNING}}
URxvt*color12: {{ACCENT_BRIGHT}}
URxvt*color13: {{SECONDARY}}
URxvt*color14: {{INFO}}
URxvt*color15: {{BRIGHT}}
