#!/usr/bin/env bash
read cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat
total1=$((user+nice+system+idle+iowait+irq+softirq+steal))
idle1=$((idle+iowait))

sleep 1

read cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat
total2=$((user+nice+system+idle+iowait+irq+softirq+steal))
idle2=$((idle+iowait))

total=$((total2-total1))
idle=$((idle2-idle1))

if [ "$total" -gt 0 ]; then
    echo "$(( (100*(total-idle))/total ))%"
else
    echo "0%"
fi
