#!/usr/bin/env zsh
#--------------------------------------------
# file:     ~/.zsh.d/aliases
# author:   Mike Redd
# version:  2.0
# desc:     Zsh loader for shared Arakiel aliases
#--------------------------------------------

if [[ -r "$HOME/lib/aliases.sh" ]]; then
    source "$HOME/lib/aliases.sh"
fi
