#!/usr/bin/env zsh
#--------------------------------------------
# file:     ~/.zsh.d/pathmarks
# author:   Mike Redd
# version:  2.0
# desc:     Zsh loader for shared Arakiel Pathmarks
#--------------------------------------------

if [[ -r "$HOME/lib/pathmarks.sh" ]]; then
    source "$HOME/lib/pathmarks.sh"
fi
