#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash.d/aliases
# author:   Mike Redd
# version:  2.0
# desc:     Bash loader for shared Arakiel aliases
#--------------------------------------------

if [[ -r "$HOME/lib/aliases.sh" ]]; then
    # shellcheck source=/dev/null
    source "$HOME/lib/aliases.sh"
fi
