#--------------------------------------------
# file:     i3blocks.conf
# author:   Mike Redd
# version:  1.2
# desc:     Minimal i3blocks config (Arakiel / Pi 5)
#--------------------------------------------

separator=true
separator_block_width=15

[disk-root]
label=SD:
command=~/.config/i3/scripts/disk /
interval=30

[disk-nvme]
label=NV:
command=~/.config/i3/scripts/disk /mnt/nvme1
interval=30

[lan]
label=LAN:
command=~/.config/i3/scripts/iface end0
interval=10

[net]
label=NET:
command=~/.config/i3/scripts/bandwidth end0
interval=2

[cpu]
label=CPU:
command=~/.config/i3/scripts/cpu_usage
interval=2

[load]
label=LD:
command=~/.config/i3/scripts/load_average
interval=5

[temp]
label=TMP:
command=~/.config/i3/scripts/temp
interval=5

[uptime]
label=UP:
command=~/.config/i3/scripts/uptime_short
interval=60

[time]
command=date '+%H:%M'
interval=1
